#!/usr/bin/env python3
"""Does a model do best on the domain it was pretrained on?

A temporal hold-out proves the test window was not memorised. It does not prove
the model has never seen that KIND of series. TimesFM's authors describe a
pretraining corpus dominated by Wikipedia pageviews -- roughly 100 billion time
points at hourly, daily, weekly and monthly granularity -- and our largest
measured advantage is on Wikipedia pageviews, at those same granularities, in a
later time window.

That could be a coincidence of the domain simply being easy for pretrained
models in general. This script separates the two, by asking a question that no
property of the series can answer: within the pretrained family, where every
model forecasts the identical series, does the TimesFM family beat the Chronos
family specifically on Wikipedia and not elsewhere? Series difficulty cancels,
because it is the same series for both. What is left is what each model read
during pretraining.

  python scripts/corpus_familiarity.py
"""
from __future__ import annotations

import argparse, json, os, sys

import numpy as np
import pandas as pd
from scipy import stats

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from scripts.significance import load_panel  # noqa: E402

FAMILY = {
    "TimesFM": ["TimesFM", "TimesFM3"],
    "Chronos": ["Chronos2", "ChronosBoltBase", "ChronosBoltSmall"],
    "Moirai": ["Moirai2"],
}
PRETRAINED = [m for ms in FAMILY.values() for m in ms]
# The domain TimesFM's paper names as the bulk of its corpus.
CORPUS_DOMAIN = ["wiki_daily", "wiki_weekly", "wiki_monthly"]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default="results/holdout_2026")
    ap.add_argument("--out", default="paper")
    args = ap.parse_args()

    panels = load_panel(args.results, "mase")
    present = [m for m in PRETRAINED if all(m in p.columns for p in panels.values())]
    tfm = [m for m in FAMILY["TimesFM"] if m in present]
    chr_ = [m for m in FAMILY["Chronos"] if m in present]
    if not tfm or not chr_:
        print("need both families present", file=sys.stderr)
        return 1

    # Per-group average rank within the pretrained family, for the table.
    per_group = {}
    rows = []
    for g, p in panels.items():
        sub = p[present]
        r = sub.rank(axis=1)
        per_group[g] = r.mean(axis=0).to_dict()
        # Two averaged families, so a single strong model cannot carry the test.
        delta = r[tfm].mean(axis=1) - r[chr_].mean(axis=1)
        for v in delta.to_numpy():
            rows.append({"group": g, "in_corpus": g in CORPUS_DOMAIN, "delta": float(v)})

    df = pd.DataFrame(rows)
    a = df.loc[df["in_corpus"], "delta"]
    b = df.loc[~df["in_corpus"], "delta"]
    u = stats.mannwhitneyu(a, b, alternative="less")
    effect = 2 * u.statistic / (len(a) * len(b)) - 1

    facts = {
        "families": {"TimesFM": tfm, "Chronos": chr_},
        "corpus_domain": CORPUS_DOMAIN,
        "median_delta_in_corpus": float(a.median()),
        "median_delta_elsewhere": float(b.median()),
        "mean_delta_in_corpus": float(a.mean()),
        "mean_delta_elsewhere": float(b.mean()),
        "n_in_corpus": int(len(a)), "n_elsewhere": int(len(b)),
        "mannwhitney_p": float(u.pvalue),
        "rank_biserial": float(effect),
        "per_group_family_rank": per_group,
    }
    os.makedirs(args.out, exist_ok=True)
    json.dump(facts, open(os.path.join(args.out, "corpus.json"), "w"), indent=2)

    p = facts["mannwhitney_p"]
    macros = {
        "CorpusDeltaWiki": f"{facts['mean_delta_in_corpus']:+.2f}",
        "CorpusDeltaOther": f"{facts['mean_delta_elsewhere']:+.2f}",
        "CorpusP": ("$<10^{-5}$" if p < 1e-5 else f"${p:.1g}$".replace("e-0", r"\times 10^{-") + "}$"
                    if "e-" in f"{p:.1g}" else f"${p:.3f}$"),
        "CorpusEffect": f"{facts['rank_biserial']:.2f}",
        "CorpusNWiki": f"{facts['n_in_corpus']:,}",
        "CorpusNOther": f"{facts['n_elsewhere']:,}",
    }
    with open(os.path.join(args.out, "tables", "corpus.tex"), "w") as fh:
        fh.write("% Generated by scripts/corpus_familiarity.py. Do not edit.\n")
        for k, v in macros.items():
            fh.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")

    print("Rank of the TimesFM family minus the Chronos family, within the")
    print("pretrained set, on identical series:")
    print(f"  Wikipedia (TimesFM's own corpus domain): mean {facts['mean_delta_in_corpus']:+.3f} "
          f"(n={facts['n_in_corpus']:,})")
    print(f"  every other domain                     : mean {facts['mean_delta_elsewhere']:+.3f} "
          f"(n={facts['n_elsewhere']:,})")
    print(f"  Mann-Whitney p={p:.2e}, rank-biserial {effect:+.3f}")
    print(f"\nwrote {args.out}/corpus.json and {args.out}/tables/corpus.tex")
    return 0


if __name__ == "__main__":
    sys.exit(main())
