#!/usr/bin/env python3
"""Build every table and every number the paper quotes, straight from results.

Nothing in the manuscript is typed by hand. A benchmark paper's numbers change
whenever a cell is re-run, and a figure copied into prose during one draft and
left there through the next is the most common way a table and its own text end
up disagreeing. So the prose reads its numbers out of paper/figures.json, and
both are regenerated by this script.

  python scripts/make_tables.py
  python scripts/make_tables.py --results results/holdout_2026 --out paper
"""
from __future__ import annotations

import argparse, glob, json, os, sys
from collections import defaultdict

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from scripts.significance import load_panel, mcb  # noqa: E402

FOUNDATION = ["ChronosBoltSmall", "ChronosBoltBase", "Chronos2",
              "TimesFM", "TimesFM3", "Moirai2", "Sundial"]
CLASSICAL = ["SeasonalNaive", "Theta", "AutoETS", "AutoARIMA"]
LEARNED = ["LightGBM", "LSTM", "NBEATS"]

GROUP_LABEL = {
    "wiki_daily": "Wikipedia (daily)", "wiki_weekly": "Wikipedia (weekly)",
    "wiki_monthly": "Wikipedia (monthly)", "weather_hourly": "Weather (hourly)",
    "airquality_hourly": "Air quality (hourly)", "energy_hourly": "Electricity (hourly)",
    "fx_daily": "Exchange rates (daily)",
}
ORDER = ["wiki_daily", "wiki_weekly", "wiki_monthly", "weather_hourly",
         "airquality_hourly", "energy_hourly", "fx_daily"]


def esc(s: str) -> str:
    return s.replace("_", r"\_")


def timing(results: str) -> pd.DataFrame:
    path = os.path.join(results, "timing.jsonl")
    rows = [json.loads(l) for l in open(path)]
    df = pd.DataFrame(rows)
    if "seed" in df.columns:
        df = df[df["seed"].isna() | (df["seed"] == 20260907)]
    return df


def mase_table(panels: dict[str, pd.DataFrame]) -> tuple[str, pd.DataFrame]:
    means = pd.DataFrame({g: p.mean(axis=0) for g, p in panels.items()})
    means = means[[g for g in ORDER if g in means.columns]]
    lines = [r"\begin{tabular}{l" + "r" * means.shape[1] + "}", r"\toprule",
             "Model & " + " & ".join(GROUP_LABEL.get(g, g) for g in means.columns) + r" \\",
             r"\midrule"]
    for block, label in ((CLASSICAL, "Classical"), (LEARNED, "Trained per dataset"),
                         (FOUNDATION, "Pretrained")):
        present = [m for m in block if m in means.index]
        if not present:
            continue
        lines.append(rf"\multicolumn{{{means.shape[1] + 1}}}{{l}}{{\emph{{{label}}}}} \\")
        for m in present:
            cells = []
            for g in means.columns:
                v = means.loc[m, g]
                best = means[g].min()
                cells.append("--" if pd.isna(v) else
                             (rf"\textbf{{{v:.3f}}}" if np.isclose(v, best) else f"{v:.3f}"))
            lines.append(f"\\quad {esc(m)} & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines), means


def rank_table(panels: dict[str, pd.DataFrame]) -> tuple[str, dict]:
    verdicts = {}
    cols = [g for g in ORDER if g in panels]
    ranks = {}
    for g in cols:
        res = mcb(panels[g])
        ranks[g] = res
        verdicts[g] = {
            "best": res.index[0],
            "friedman_p": res.attrs["friedman_p"],
            "n_series": res.attrs["n_series"],
            "tied_with_best": list(res.index[res["indistinguishable_from_best"]]),
        }
    models = sorted({m for g in cols for m in ranks[g].index},
                    key=lambda m: np.mean([ranks[g]["avg_rank"].get(m, np.nan) for g in cols
                                           if m in ranks[g].index]))
    lines = [r"\begin{tabular}{l" + "r" * len(cols) + "}", r"\toprule",
             "Model & " + " & ".join(GROUP_LABEL.get(g, g) for g in cols) + r" \\",
             r"\midrule"]
    for m in models:
        cells = []
        for g in cols:
            if m not in ranks[g].index:
                cells.append("--"); continue
            r = ranks[g].loc[m]
            cell = f"{r['avg_rank']:.2f}"
            if r["indistinguishable_from_best"]:
                cell = rf"\underline{{{cell}}}"
            cells.append(cell)
        lines.append(f"{esc(m)} & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines), verdicts


def cost_table(t: pd.DataFrame) -> tuple[str, dict]:
    per = t.groupby("model")["seconds_per_series"].median().sort_values()
    lines = [r"\begin{tabular}{lrr}", r"\toprule",
             r"Model & Median s/series & Slowdown vs.\ fastest \\", r"\midrule"]
    base = per[per > 0].min()
    for m, v in per.items():
        lines.append(f"{esc(m)} & {v:.4f} & " +
                     ("--" if v <= 0 else f"{v / base:.0f}$\\times$") + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    facts = {"median_seconds_per_series": {k: float(v) for k, v in per.items()}}
    # The cost gap is NOT a single number: it is 17x on weekly data and 2,700x
    # on hourly, because an ARIMA search grows with series length and season
    # while a forward pass does not. Quoting the median alone understates it and
    # quoting the maximum alone overstates it, so both are carried through to
    # the prose along with the group each came from.
    wide = t.pivot_table(index="group", columns="model", values="seconds_per_series")
    if "AutoARIMA" in wide.columns and "Chronos2" in wide.columns:
        ratio = (wide["AutoARIMA"] / wide["Chronos2"]).dropna()
        if len(ratio):
            facts["arima_over_Chronos2_median"] = float(ratio.median())
            facts["arima_over_Chronos2_max"] = float(ratio.max())
            facts["arima_over_Chronos2_max_group"] = str(ratio.idxmax())
            facts["arima_over_Chronos2_min"] = float(ratio.min())
            facts["arima_n_groups"] = int(len(ratio))
    return "\n".join(lines), facts


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default="results/holdout_2026")
    ap.add_argument("--out", default="paper")
    args = ap.parse_args()

    panels = load_panel(args.results, "mase")
    if not panels:
        print("no results found", file=sys.stderr)
        return 1
    os.makedirs(os.path.join(args.out, "tables"), exist_ok=True)

    mase_tex, means = mase_table(panels)
    rank_tex, verdicts = rank_table(panels)
    t = timing(args.results)
    cost_tex, cost_facts = cost_table(t)

    for name, tex in (("mase", mase_tex), ("ranks", rank_tex), ("cost", cost_tex)):
        open(os.path.join(args.out, "tables", f"{name}.tex"), "w").write(tex + "\n")

    # The claims the prose makes, computed rather than remembered.
    facts: dict = {"groups": {}, "cost": cost_facts,
                   "n_cells": int(len(t)), "n_models": int(t["model"].nunique())}
    for g, v in verdicts.items():
        col = means[g].dropna()
        best_f = col[[m for m in col.index if m in FOUNDATION]].min() if any(
            m in FOUNDATION for m in col.index) else np.nan
        best_c = col[[m for m in col.index if m in CLASSICAL]].min() if any(
            m in CLASSICAL for m in col.index) else np.nan
        facts["groups"][g] = {
            **v, "label": GROUP_LABEL.get(g, g),
            "best_foundation_mase": None if pd.isna(best_f) else float(best_f),
            "best_classical_mase": None if pd.isna(best_c) else float(best_c),
            "foundation_gain_pct": None if (pd.isna(best_f) or pd.isna(best_c) or best_c == 0)
                                   else float((best_c - best_f) / best_c * 100.0),
            "best_is_foundation": v["best"] in FOUNDATION,
            "naive_tied_with_best": "SeasonalNaive" in v["tied_with_best"],
        }
    json.dump(facts, open(os.path.join(args.out, "figures.json"), "w"), indent=2)

    # Numbers the prose quotes, emitted as macros so a sentence cannot drift
    # from the table above it between one re-run and the next.
    gains = {g: f["foundation_gain_pct"] for g, f in facts["groups"].items()
             if f["foundation_gain_pct"] is not None}
    n_best = sum(1 for f in facts["groups"].values() if f["best_is_foundation"])
    # Ranking first where the Friedman test does not reject is not a win; on
    # exchange rates a pretrained model tops the column and the benchmark has
    # detected nothing at all. Counting those as wins would be the exact
    # overclaim this paper exists to argue against.
    n_best_sig = sum(1 for f in facts["groups"].values()
                     if f["best_is_foundation"] and f["friedman_p"] < 0.05)
    n_null = sum(1 for f in facts["groups"].values() if f["friedman_p"] >= 0.05)
    arima_groups = sorted(t.loc[t["model"] == "AutoARIMA", "group"].unique())
    arima_beaten = [g for g in arima_groups
                    if g in means.columns and not pd.isna(means.loc["AutoARIMA", g])
                    and means[g].min() < means.loc["AutoARIMA", g]]
    macros = {
        "MaxGain": f"{max(gains.values()):.0f}\\%" if gains else "??",
        "MaxGainGroup": GROUP_LABEL.get(max(gains, key=gains.get), "??").lower() if gains else "??",
        "NumGroups": str(len(facts["groups"])),
        "NumGroupsFoundationBest": str(n_best),
        "NumGroupsFoundationBestSig": str(n_best_sig),
        "NumGroupsNoDifference": str(n_null),
        "NumArimaGroups": str(len(arima_groups)),
        "NumArimaBeaten": str(len(arima_beaten)),
        "ArimaMedianSlowdown": (f"{cost_facts['arima_over_Chronos2_median']:,.0f}"
                                if "arima_over_Chronos2_median" in cost_facts else "??"),
        "ArimaMaxSlowdown": (f"{cost_facts['arima_over_Chronos2_max']:,.0f}"
                             if "arima_over_Chronos2_max" in cost_facts else "??"),
        "ArimaMaxGroup": (GROUP_LABEL.get(cost_facts["arima_over_Chronos2_max_group"], "??").lower()
                          if "arima_over_Chronos2_max_group" in cost_facts else "??"),
        "ArimaMinSlowdown": (f"{cost_facts['arima_over_Chronos2_min']:,.0f}"
                             if "arima_over_Chronos2_min" in cost_facts else "??"),
    }
    with open(os.path.join(args.out, "tables", "claims.tex"), "w") as fh:
        fh.write("% Generated by scripts/make_tables.py. Do not edit.\n")
        for k, v in macros.items():
            fh.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")

    print(f"wrote {args.out}/tables/*.tex and {args.out}/figures.json")
    for g in ORDER:
        if g not in facts["groups"]:
            continue
        f = facts["groups"][g]
        gain = f["foundation_gain_pct"]
        print(f"  {f['label']:24} best={f['best']:16} "
              f"gain over best classical: {'n/a' if gain is None else f'{gain:+5.1f}%'}"
              f"{'   [naive is tied]' if f['naive_tied_with_best'] else ''}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
